### ISSUE TITLE
Using the `react-frp` bucklescript files

### ISSUE THREAD

**Issue by idkjs** [Denommus/react-react#5]
I notice you guys just updated this project. Thanks for that. Any plans on including `"react-frp": "git://github.com/Denommus/react#bucklescript-files",` in the package? Is there some reason we are installing from git?

**Comment by Denommus** [comment]
There's no reason in particular, it's just that Erratique's React is not my library, so I didn't feel comfortable to package it with my library.

But given that it hasn't been receiving much updates, perhaps I should consider hosting it in npm instead of pulling from git. What's your opinion on it?

**Comment by idkjs** [comment]
I already did the same. You should do that.

**Comment by idkjs** [comment]
Check this out. https://idkjs.github.io/reason-neon-clock/
